version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  [
    'dataviz',
    'deepmerge',
    'csstype',
    'buildable',
    'pkgs',
    'arcsin',
    'crtl',
    'crtr',
    'crbr',
    'crbl',
  ]
import: []
