import {
  PrendaThemeOptions,
  TertiaryColor,
  muiTheme,
  prendaTheme,
} from './theme';
import {
  colors,
  colorsPrendaBlue,
  colorsPrendaLightBlue,
  colorsPrendaOrange,
  colorsPrendaPeach,
  colorsPrendaNavy,
  colorsPrendaLightGrey,
  colorsPrendaMediumGrey,
  colorsPrendaDarkGrey,
  colorsPrendaWhite,
  colorsPrimaryAction,
  colorsSuccess,
  colorsWarning,
  colorsError,
  colorsBackgroundNavy,
  colorsBackgroundBlue,
  colorsBackgroundLightGrey,
  colorsBackgroundLightBlue,
  colorsBackgroundWhite,
  colorsTextIconOnDarkHighContrast,
  colorsTextIconOnDarkLowContrast,
  colorsTextIconOnLightHighContrast,
  colorsTextIconOnLightLowContrast,
  colorsBlue,
  colorsGreen,
  colorsOrange,
  colorsPurple,
  colorsRed,
  colorsYellow,
} from './colors';
import { SparkThemeProvider } from './Provider';

export {
  SparkThemeProvider,
  PrendaThemeOptions,
  TertiaryColor,
  muiTheme,
  prendaTheme,
  colors,
  colorsPrendaBlue,
  colorsPrendaLightBlue,
  colorsPrendaOrange,
  colorsPrendaPeach,
  colorsPrendaNavy,
  colorsPrendaLightGrey,
  colorsPrendaMediumGrey,
  colorsPrendaDarkGrey,
  colorsPrendaWhite,
  colorsPrimaryAction,
  colorsSuccess,
  colorsWarning,
  colorsError,
  colorsBackgroundNavy,
  colorsBackgroundBlue,
  colorsBackgroundLightGrey,
  colorsBackgroundLightBlue,
  colorsBackgroundWhite,
  colorsTextIconOnDarkHighContrast,
  colorsTextIconOnDarkLowContrast,
  colorsTextIconOnLightHighContrast,
  colorsTextIconOnLightLowContrast,
  colorsBlue,
  colorsGreen,
  colorsOrange,
  colorsPurple,
  colorsRed,
  colorsYellow,
};
