name: 'Chromatic'

on:  
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  chromatic-deployment:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
        
      - name: Install Dependencies
        run: npm i

      - name: Build Storybook
        run: npx nx run spark:build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: dist/storybook/spark
