name: Continuous Integration Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Increase system files monitor limit
        run: sudo sysctl fs.inotify.max_user_watches=524288

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: NPM clean install
        run: npm ci

      - name: Lint
        run: npm run affected:lint

      - name: Check format
        run: npm run format:check

      - name: Unit test project spark
        run: npx nx run spark:test

      - name: Unit test project spark-icons
        run: npx nx run spark-icons:test

      - name: End-to-end test project spark-e2e
        run: npx nx run spark-e2e:e2e
