name: Continuous Integration Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          
      - name: Yarn Clean Install
        run: yarn install --frozen-install

      - name: Yarn Test
        run: yarn test