name: Continuous Integration Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: NPM clean install
        run: npm ci

      - name: Spark Jest tests
        run: npx nx run spark:test

      - name: Spark Cypress end-to-end tests
        run: npx nx run spark-e2e:e2e
